[package]
name = "hazmatdev"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.9.0"
anyhow = "1.0.102"
argon2 = "0.5.3"
bytesize = "2.3.1"
clap = { version = "4.6.1", features = ["derive"] }
ctr = "0.10.0"
indicatif = "0.18.4"
libc = "0.2.186"
libublk = "0.4.6"
num-traits = "0.2.19"
rand = "0.10.1"
rand_chacha = "0.10.0"
rpassword = "7.5.2"
signal-hook = "0.4.4"
smol = "2.0.2"

[lints.clippy]
clone_on_copy = "deny"
redundant_clone = "deny"
